# -*- coding: utf-8 -*-
"""Entropy-Aware Neuroplastic Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPQ9moA4PL_gabKRSlZPvG0NgBxa1vYW
"""

# mkdir '/content/drive/MyDrive/Neuroplastic-NNs'

cd /content/drive/MyDrive/Neuroplastic-NNs

"""# Full Run"""

#!/usr/bin/env python3
# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  EXPERIMENT 6: COMPLETE NEUROPLASTICITY                                 ║
# ║  Conv Front-End + Growing Skip-MLP + BatchNorm + Synaptic Pruning       ║
# ║                                                                          ║
# ║  The final biological analogy:                                           ║
# ║    • Growth (synaptogenesis) — new neurons when struggling               ║
# ║    • Pruning (synaptic pruning) — remove weak/redundant neurons          ║
# ║    • Conv layers (visual cortex V1/V2) — spatial feature extraction      ║
# ║    • Skip connections (cortical highways) — gradient flow                ║
# ║    • BatchNorm (homeostatic plasticity) — activity normalisation         ║
# ║    • GradCAM (neural imaging) — watch the brain develop                  ║
# ║                                                                          ║
# ║  Run in Google Colab: Runtime → Run all (GPU recommended)                ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# %% Cell 1 — Setup
# !pip install torch torchvision scipy matplotlib --quiet

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import math, time, copy, warnings, os, gc, json
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D
from scipy.spatial.distance import cdist

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as T

warnings.filterwarnings("ignore")
torch.manual_seed(42)
np.random.seed(42)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device  : {DEVICE}")
print(f"PyTorch : {torch.__version__}")

OUT_DIR = "/content/drive/MyDrive/Neuroplastic-NNs"
os.makedirs(OUT_DIR, exist_ok=True)
print(f"Output  : {OUT_DIR}")

# ══════════════════════════════════════════════════════════════════════
# %% Cell 2 — CIFAR-10 Dataset
# ══════════════════════════════════════════════════════════════════════
CIFAR_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR_STD  = (0.2470, 0.2435, 0.2616)

transform_train = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
])
transform_test = T.Compose([
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
])

train_set = torchvision.datasets.CIFAR10(root="./data", train=True,  download=True, transform=transform_train)
test_set  = torchvision.datasets.CIFAR10(root="./data", train=False, download=True, transform=transform_test)

# Also keep a raw test set for GradCAM visualisation (no normalisation)
transform_raw = T.Compose([T.ToTensor()])
raw_test_set = torchvision.datasets.CIFAR10(root="./data", train=False, download=False, transform=transform_raw)

train_loader = torch.utils.data.DataLoader(train_set, batch_size=128, shuffle=True, num_workers=2, pin_memory=True)
test_loader  = torch.utils.data.DataLoader(test_set,  batch_size=256, shuffle=False, num_workers=2, pin_memory=True)

CLASSES = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
print(f"Train: {len(train_set):,}  Test: {len(test_set):,}")


# ══════════════════════════════════════════════════════════════════════
# %% Cell 3 — Model: Conv Front-End + Growing Skip-MLP
# ══════════════════════════════════════════════════════════════════════

class ConvBlock(nn.Module):
    """Conv3x3 → BatchNorm → ReLU [→ MaxPool]"""
    def __init__(self, in_ch, out_ch, pool=False):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False)
        self.bn   = nn.BatchNorm2d(out_ch)
        self.pool = nn.MaxPool2d(2) if pool else nn.Identity()

    def forward(self, x):
        return self.pool(F.relu(self.bn(self.conv(x))))


class ResMLPBlock(nn.Module):
    """Linear → BN → ReLU → Linear → BN + skip → ReLU"""
    def __init__(self, width):
        super().__init__()
        self.fc1 = nn.Linear(width, width)
        self.bn1 = nn.BatchNorm1d(width)
        self.fc2 = nn.Linear(width, width)
        self.bn2 = nn.BatchNorm1d(width)
        # FixUp-style: init fc2 near-zero so block starts as pass-through
        nn.init.zeros_(self.fc2.weight)
        nn.init.zeros_(self.fc2.bias)

    @property
    def width(self):
        return self.fc1.in_features

    def forward(self, x):
        identity = x
        out = F.relu(self.bn1(self.fc1(x)))
        out = self.bn2(self.fc2(out))
        return F.relu(out + identity)


class NeuroplasticityNet(nn.Module):
    """
    Conv front-end (fixed structure, prunable filters) +
    Growing Skip-MLP tail (growable width & depth, prunable neurons).

    Architecture:
      [ConvBlock×3] → GAP → flatten →
      [ResMLPBlock×N] → Output head
    """
    def __init__(self, conv_channels=(16, 32, 64), init_mlp_width=64, init_blocks=2, n_classes=10):
        super().__init__()
        self.n_classes = n_classes

        # Conv front-end
        chs = list(conv_channels)
        self.conv_blocks = nn.ModuleList()
        in_ch = 3
        for i, out_ch in enumerate(chs):
            pool = (i >= 1)  # pool after 2nd and 3rd conv
            self.conv_blocks.append(ConvBlock(in_ch, out_ch, pool=pool))
            in_ch = out_ch
        self.conv_out_ch = chs[-1]

        # Projection from conv features to MLP width
        self.proj = nn.Linear(self.conv_out_ch, init_mlp_width)
        self.proj_bn = nn.BatchNorm1d(init_mlp_width)

        # Growing MLP blocks
        self.mlp_blocks = nn.ModuleList()
        for _ in range(init_blocks):
            self.mlp_blocks.append(ResMLPBlock(init_mlp_width))

        # Output head
        self.head = nn.Linear(init_mlp_width, n_classes)

        # Track architecture history
        self._growth_log = []
        self._prune_log  = []

    @property
    def mlp_width(self):
        return self.proj.out_features

    @property
    def n_blocks(self):
        return len(self.mlp_blocks)

    def forward(self, x):
        # Conv front-end
        for blk in self.conv_blocks:
            x = blk(x)
        # GAP + flatten
        x = F.adaptive_avg_pool2d(x, 1).view(x.size(0), -1)
        # Projection
        x = F.relu(self.proj_bn(self.proj(x)))
        # MLP blocks
        for blk in self.mlp_blocks:
            x = blk(x)
        # Output
        return self.head(x)

    def represent(self, x):
        """Penultimate activations (before head)."""
        with torch.no_grad():
            for blk in self.conv_blocks:
                x = blk(x)
            x = F.adaptive_avg_pool2d(x, 1).view(x.size(0), -1)
            x = F.relu(self.proj_bn(self.proj(x)))
            for blk in self.mlp_blocks:
                x = blk(x)
        return x

    def n_params(self):
        return sum(p.numel() for p in self.parameters())

    def weight_matrices(self):
        """Return weight tensors for IT metrics."""
        mats = [self.proj.weight.detach().cpu().numpy()]
        for blk in self.mlp_blocks:
            mats.append(blk.fc1.weight.detach().cpu().numpy())
            mats.append(blk.fc2.weight.detach().cpu().numpy())
        mats.append(self.head.weight.detach().cpu().numpy())
        return mats


# ══════════════════════════════════════════════════════════════════════
# %% Cell 4 — Growth Operators
# ══════════════════════════════════════════════════════════════════════

WIDTH_DELTA = 32

def grow_width(model, delta=WIDTH_DELTA):
    """Grow all MLP layers wider by delta neurons (Net2Net style)."""
    old_w = model.mlp_width
    new_w = old_w + delta
    device = next(model.parameters()).device

    # Projection layer
    new_proj = nn.Linear(model.conv_out_ch, new_w).to(device)
    new_proj.weight.data[:old_w] = model.proj.weight.data
    new_proj.weight.data[old_w:] = torch.randn(delta, model.conv_out_ch, device=device) * 0.01
    new_proj.bias.data[:old_w] = model.proj.bias.data
    new_proj.bias.data[old_w:] = 0
    model.proj = new_proj

    new_proj_bn = nn.BatchNorm1d(new_w).to(device)
    new_proj_bn.weight.data[:old_w] = model.proj_bn.weight.data
    new_proj_bn.bias.data[:old_w] = model.proj_bn.bias.data
    new_proj_bn.running_mean[:old_w] = model.proj_bn.running_mean
    new_proj_bn.running_var[:old_w] = model.proj_bn.running_var
    model.proj_bn = new_proj_bn

    # Each MLP block
    for blk in model.mlp_blocks:
        # fc1: [old_w, old_w] → [new_w, new_w]
        new_fc1 = nn.Linear(new_w, new_w).to(device)
        new_fc1.weight.data[:old_w, :old_w] = blk.fc1.weight.data
        new_fc1.weight.data[old_w:, :old_w] = torch.randn(delta, old_w, device=device) * 0.001
        new_fc1.weight.data[:old_w, old_w:] = torch.randn(old_w, delta, device=device) * 0.01
        new_fc1.weight.data[old_w:, old_w:] = torch.randn(delta, delta, device=device) * 0.001
        new_fc1.bias.data[:old_w] = blk.fc1.bias.data
        new_fc1.bias.data[old_w:] = 0
        blk.fc1 = new_fc1

        new_bn1 = nn.BatchNorm1d(new_w).to(device)
        new_bn1.weight.data[:old_w] = blk.bn1.weight.data
        new_bn1.bias.data[:old_w] = blk.bn1.bias.data
        new_bn1.running_mean[:old_w] = blk.bn1.running_mean
        new_bn1.running_var[:old_w] = blk.bn1.running_var
        blk.bn1 = new_bn1

        # fc2
        new_fc2 = nn.Linear(new_w, new_w).to(device)
        new_fc2.weight.data[:old_w, :old_w] = blk.fc2.weight.data
        new_fc2.weight.data[old_w:, :] = 0  # near-zero for new outputs
        new_fc2.weight.data[:, old_w:] = torch.randn(new_w, delta, device=device) * 0.001
        new_fc2.bias.data[:old_w] = blk.fc2.bias.data
        new_fc2.bias.data[old_w:] = 0
        blk.fc2 = new_fc2

        new_bn2 = nn.BatchNorm1d(new_w).to(device)
        new_bn2.weight.data[:old_w] = blk.bn2.weight.data
        new_bn2.bias.data[:old_w] = blk.bn2.bias.data
        new_bn2.running_mean[:old_w] = blk.bn2.running_mean
        new_bn2.running_var[:old_w] = blk.bn2.running_var
        blk.bn2 = new_bn2

    # Output head
    new_head = nn.Linear(new_w, model.n_classes).to(device)
    new_head.weight.data[:, :old_w] = model.head.weight.data
    new_head.weight.data[:, old_w:] = torch.randn(model.n_classes, delta, device=device) * 0.001
    new_head.bias.data = model.head.bias.data.clone()
    model.head = new_head

    return new_w


def grow_depth(model):
    """Add a new ResMLPBlock (near-identity)."""
    device = next(model.parameters()).device
    w = model.mlp_width
    new_block = ResMLPBlock(w).to(device)
    model.mlp_blocks.append(new_block)
    return len(model.mlp_blocks)


# ══════════════════════════════════════════════════════════════════════
# %% Cell 5 — Synaptic Pruning
# ══════════════════════════════════════════════════════════════════════

def layer_cosine_triage(model, dataloader, device, threshold=0.95):
    """
    Stage 1: Identify near-identity layers by measuring cosine similarity
    between each MLP block's input and output activations.
    Returns list of (block_idx, cosine_sim) for blocks above threshold.
    """
    model.eval()
    block_scores = []

    # Collect a minibatch
    x_batch, _ = next(iter(dataloader))
    x_batch = x_batch[:256].to(device)

    with torch.no_grad():
        # Forward through conv
        h = x_batch
        for blk in model.conv_blocks:
            h = blk(h)
        h = F.adaptive_avg_pool2d(h, 1).view(h.size(0), -1)
        h = F.relu(model.proj_bn(model.proj(h)))

        # Check each MLP block
        for i, blk in enumerate(model.mlp_blocks):
            h_in = h.clone()
            h_out = blk(h)

            # Cosine similarity per sample, then average
            cos = F.cosine_similarity(h_in, h_out, dim=1).mean().item()
            block_scores.append((i, cos))
            h = h_out

    # Flag blocks with cos > threshold (near-identity → weak)
    flagged = [(idx, cs) for idx, cs in block_scores if cs > threshold]
    return block_scores, flagged


def compute_neuron_importance(model, dataloader, device, block_idx):
    """
    Stage 2: For a flagged MLP block, compute per-neuron importance using:
      - Magnitude: L2 norm of outgoing weights from fc2
      - Fisher: per-neuron gradient sensitivity
      - BN gamma: BatchNorm scaling factor magnitude

    Returns importance scores [width] — lower = more prunable.
    """
    blk = model.mlp_blocks[block_idx]
    w = blk.width

    # Magnitude score: L2 norm of each neuron's outgoing weights in fc2
    # fc2 maps from width → width, each row is one neuron's contribution
    mag_score = blk.fc2.weight.data.norm(dim=0).cpu().numpy()  # [width]

    # BN gamma score
    bn_gamma = blk.bn1.weight.data.abs().cpu().numpy()  # [width]

    # Fisher score: gradient magnitude per neuron
    model.train()
    fisher_score = np.zeros(w, dtype=np.float32)
    criterion = nn.CrossEntropyLoss()

    x_batch, y_batch = next(iter(dataloader))
    x_batch, y_batch = x_batch[:128].to(device), y_batch[:128].to(device)

    model.zero_grad()
    output = model(x_batch)
    loss = criterion(output, y_batch)
    loss.backward()

    # Per-neuron Fisher from fc1 gradients
    if blk.fc1.weight.grad is not None:
        fisher_score = (blk.fc1.weight.grad ** 2).sum(dim=1).cpu().numpy()  # [width]

    model.eval()

    # Composite score (normalise each to [0,1] then average)
    def normalise(x):
        mn, mx = x.min(), x.max()
        return (x - mn) / (mx - mn + 1e-12)

    importance = (normalise(mag_score) + normalise(bn_gamma) + normalise(fisher_score)) / 3.0
    return importance


def prune_neurons(model, block_idx, neuron_mask, device):
    """
    Remove neurons from a specific MLP block where neuron_mask is False.
    Also adjusts adjacent layers and BN parameters.

    neuron_mask: bool array [width], True = keep, False = prune
    """
    keep_idx = torch.where(torch.tensor(neuron_mask))[0].to(device)
    new_w = int(keep_idx.shape[0])
    blk = model.mlp_blocks[block_idx]
    old_w = blk.width

    if new_w == old_w:
        return 0  # nothing to prune

    # fc1: [old_w, old_w] → [new_w, ?]
    # fc1 takes input from previous block (or proj), outputs to this block's neurons
    # We need to keep rows corresponding to kept neurons AND
    # adjust input dim if previous block was also pruned (handled separately)
    new_fc1 = nn.Linear(new_w, new_w).to(device)
    new_fc1.weight.data = blk.fc1.weight.data[keep_idx][:, keep_idx]
    new_fc1.bias.data = blk.fc1.bias.data[keep_idx]

    new_bn1 = nn.BatchNorm1d(new_w).to(device)
    new_bn1.weight.data = blk.bn1.weight.data[keep_idx]
    new_bn1.bias.data = blk.bn1.bias.data[keep_idx]
    new_bn1.running_mean = blk.bn1.running_mean[keep_idx]
    new_bn1.running_var = blk.bn1.running_var[keep_idx]

    new_fc2 = nn.Linear(new_w, new_w).to(device)
    new_fc2.weight.data = blk.fc2.weight.data[keep_idx][:, keep_idx]
    new_fc2.bias.data = blk.fc2.bias.data[keep_idx]

    new_bn2 = nn.BatchNorm1d(new_w).to(device)
    new_bn2.weight.data = blk.bn2.weight.data[keep_idx]
    new_bn2.bias.data = blk.bn2.bias.data[keep_idx]
    new_bn2.running_mean = blk.bn2.running_mean[keep_idx]
    new_bn2.running_var = blk.bn2.running_var[keep_idx]

    blk.fc1 = new_fc1
    blk.bn1 = new_bn1
    blk.fc2 = new_fc2
    blk.bn2 = new_bn2

    # Adjust adjacent layers
    # If this is the first block, adjust proj output
    if block_idx == 0:
        new_proj = nn.Linear(model.conv_out_ch, new_w).to(device)
        new_proj.weight.data = model.proj.weight.data[keep_idx]
        new_proj.bias.data = model.proj.bias.data[keep_idx]
        model.proj = new_proj

        new_proj_bn = nn.BatchNorm1d(new_w).to(device)
        new_proj_bn.weight.data = model.proj_bn.weight.data[keep_idx]
        new_proj_bn.bias.data = model.proj_bn.bias.data[keep_idx]
        new_proj_bn.running_mean = model.proj_bn.running_mean[keep_idx]
        new_proj_bn.running_var = model.proj_bn.running_var[keep_idx]
        model.proj_bn = new_proj_bn
    else:
        # Adjust previous block's output dimension
        prev = model.mlp_blocks[block_idx - 1]
        new_fc2_prev = nn.Linear(prev.width, new_w).to(device)
        new_fc2_prev.weight.data = prev.fc2.weight.data[keep_idx][:, :prev.width]
        new_fc2_prev.bias.data = prev.fc2.bias.data[keep_idx]
        prev.fc2 = new_fc2_prev

        new_bn2_prev = nn.BatchNorm1d(new_w).to(device)
        new_bn2_prev.weight.data = prev.bn2.weight.data[keep_idx]
        new_bn2_prev.bias.data = prev.bn2.bias.data[keep_idx]
        new_bn2_prev.running_mean = prev.bn2.running_mean[keep_idx]
        new_bn2_prev.running_var = prev.bn2.running_var[keep_idx]
        prev.bn2 = new_bn2_prev

    # If this is the last block, adjust head input
    if block_idx == len(model.mlp_blocks) - 1:
        new_head = nn.Linear(new_w, model.n_classes).to(device)
        new_head.weight.data = model.head.weight.data[:, keep_idx]
        new_head.bias.data = model.head.bias.data.clone()
        model.head = new_head

    # Adjust next block's input if exists
    if block_idx < len(model.mlp_blocks) - 1:
        nxt = model.mlp_blocks[block_idx + 1]
        new_fc1_nxt = nn.Linear(new_w, nxt.width).to(device)
        new_fc1_nxt.weight.data = nxt.fc1.weight.data[:, keep_idx]
        new_fc1_nxt.bias.data = nxt.fc1.bias.data.clone()
        nxt.fc1 = new_fc1_nxt

    n_pruned = old_w - new_w
    return n_pruned


def synaptic_pruning_cycle(model, dataloader, device, prune_ratio=0.15):
    """
    Full pruning cycle:
      1. Layer triage (cosine similarity)
      2. Neuron importance scoring in flagged layers
      3. Prune bottom prune_ratio neurons
    Returns total neurons pruned.
    """
    all_scores, flagged = layer_cosine_triage(model, dataloader, device, threshold=0.90)
    total_pruned = 0

    if not flagged:
        # Even if no layer is near-identity, check the one with highest cosine
        if all_scores:
            best = max(all_scores, key=lambda x: x[1])
            if best[1] > 0.80:  # still somewhat redundant
                flagged = [best]

    for block_idx, cos_sim in flagged:
        blk = model.mlp_blocks[block_idx]
        w = blk.width
        if w <= 16:  # don't prune below minimum width
            continue

        importance = compute_neuron_importance(model, dataloader, device, block_idx)
        n_to_prune = max(1, int(w * prune_ratio))
        n_to_prune = min(n_to_prune, w - 16)  # keep at least 16 neurons

        # Prune the least important neurons
        threshold_idx = np.argsort(importance)[:n_to_prune]
        mask = np.ones(w, dtype=bool)
        mask[threshold_idx] = False

        n = prune_neurons(model, block_idx, mask, device)
        total_pruned += n
        print(f"    [Prune] Block {block_idx}: cos={cos_sim:.3f}, "
              f"pruned {n}/{w} neurons → {w-n}")

    return total_pruned


# ══════════════════════════════════════════════════════════════════════
# %% Cell 6 — Conv Layer Importance & Protection
# ══════════════════════════════════════════════════════════════════════

def conv_importance_scores(model, dataloader, device, n_samples=128):
    """
    Compute importance score for each conv layer based on mean GradCAM
    activation magnitude. Layers with high scores are protected from pruning.
    """
    model.eval()
    x_batch, y_batch = next(iter(dataloader))
    x_batch, y_batch = x_batch[:n_samples].to(device), y_batch[:n_samples].to(device)

    scores = []
    for i, blk in enumerate(model.conv_blocks):
        activations = []
        gradients = []

        def fwd_hook(module, inp, out):
            activations.append(out)

        def bwd_hook(module, grad_in, grad_out):
            gradients.append(grad_out[0])

        fh = blk.conv.register_forward_hook(fwd_hook)
        bh = blk.conv.register_full_backward_hook(bwd_hook)

        model.zero_grad()
        output = model(x_batch)
        # Use predicted class for GradCAM
        pred = output.argmax(dim=1)
        loss = F.cross_entropy(output, pred)
        loss.backward()

        if activations and gradients:
            act = activations[0]
            grad = gradients[0]
            # GradCAM weights: global average pool of gradients
            weights = grad.mean(dim=[2, 3], keepdim=True)
            cam = (weights * act).sum(dim=1)
            cam = F.relu(cam)
            # Importance = mean activation magnitude normalised by spatial size
            spatial = cam.shape[1] * cam.shape[2]
            score = cam.mean().item() / (spatial + 1e-8) * 1e4
            scores.append(score)
        else:
            scores.append(0.0)

        fh.remove()
        bh.remove()

    model.eval()
    return scores


# ══════════════════════════════════════════════════════════════════════
# %% Cell 7 — GradCAM Visualisation
# ══════════════════════════════════════════════════════════════════════

def generate_gradcam(model, x_input, target_layer, device):
    """Generate GradCAM heatmap for a single image at a specific conv layer."""
    model.eval()
    activations = []
    gradients = []

    def fwd_hook(m, inp, out):
        activations.append(out.detach())
    def bwd_hook(m, grad_in, grad_out):
        gradients.append(grad_out[0].detach())

    fh = target_layer.register_forward_hook(fwd_hook)
    bh = target_layer.register_full_backward_hook(bwd_hook)

    x = x_input.unsqueeze(0).to(device)
    output = model(x)
    pred_class = output.argmax(dim=1).item()

    model.zero_grad()
    output[0, pred_class].backward()

    act = activations[0].squeeze(0)   # [C, H, W]
    grad = gradients[0].squeeze(0)    # [C, H, W]

    weights = grad.mean(dim=[1, 2])   # [C]
    cam = (weights.unsqueeze(1).unsqueeze(2) * act).sum(dim=0)  # [H, W]
    cam = F.relu(cam)
    cam = cam - cam.min()
    if cam.max() > 0:
        cam = cam / cam.max()

    fh.remove()
    bh.remove()

    return cam.cpu().numpy(), pred_class


def snapshot_gradcam(model, sample_images, sample_labels, epoch, device, tag=""):
    """
    Generate GradCAM grid: rows = conv layers, columns = sample images.
    """
    model.eval()
    n_layers = len(model.conv_blocks)
    n_samples = len(sample_images)

    fig, axes = plt.subplots(n_layers + 1, n_samples, figsize=(2.5 * n_samples, 2.5 * (n_layers + 1)))
    fig.suptitle(f"GradCAM @ Epoch {epoch} {tag}", fontsize=14, fontweight='bold')

    for j in range(n_samples):
        # Original image
        img = sample_images[j]
        if img.shape[0] == 3:
            img_show = img.permute(1, 2, 0).numpy()
        else:
            img_show = img.numpy()
        img_show = np.clip(img_show, 0, 1)

        axes[0, j].imshow(img_show)
        axes[0, j].set_title(f"{CLASSES[sample_labels[j]]}", fontsize=9)
        axes[0, j].axis('off')

        # GradCAM per conv layer
        norm_img = T.Normalize(CIFAR_MEAN, CIFAR_STD)(img)
        for i, blk in enumerate(model.conv_blocks):
            cam, pred = generate_gradcam(model, norm_img, blk.conv, device)
            cam_resized = np.array(
                __import__('PIL').Image.fromarray((cam * 255).astype(np.uint8)).resize((32, 32))
            ).astype(np.float32) / 255.0

            axes[i + 1, j].imshow(img_show)
            axes[i + 1, j].imshow(cam_resized, alpha=0.5, cmap='jet')
            axes[i + 1, j].axis('off')
            if j == 0:
                axes[i + 1, j].set_ylabel(f"Conv {i+1}", fontsize=9)

    plt.tight_layout()
    path = os.path.join(OUT_DIR, f"gradcam_epoch{epoch:03d}{tag}.png")
    plt.savefig(path, dpi=120, bbox_inches='tight')
    plt.close()
    print(f"    [GradCAM] Saved: {path}")
    return path


# ══════════════════════════════════════════════════════════════════════
# %% Cell 8 — IT Metrics
# ══════════════════════════════════════════════════════════════════════

def effective_rank(model):
    ranks = []
    for W in model.weight_matrices():
        s = np.linalg.svd(W.astype(np.float64), compute_uv=False)
        s = s[s > 1e-10]
        if len(s) == 0: ranks.append(1.0); continue
        p = s / s.sum()
        ranks.append(float(np.exp(-np.sum(p * np.log(p + 1e-12)))))
    return float(np.mean(ranks))


def fisher_trace(model, dataloader, device):
    model.eval()
    x, y = next(iter(dataloader))
    x, y = x[:256].to(device), y[:256].to(device)
    model.zero_grad()
    out = model(x)
    loss = F.cross_entropy(out, y)
    loss.backward()
    tr = 0.0
    for p in model.parameters():
        if p.grad is not None:
            tr += float((p.grad ** 2).sum().item())
    model.zero_grad()
    return tr


def mutual_info_ib(model, dataloader, device, n_bins=28):
    model.eval()
    xs, ys = [], []
    for xb, yb in dataloader:
        xs.append(xb); ys.append(yb)
        if sum(len(y) for y in ys) >= 2000:
            break
    X = torch.cat(xs)[:2000].to(device)
    y = torch.cat(ys)[:2000].numpy()

    reps = model.represent(X).cpu().numpy()
    rc = (reps - reps.mean(0)).astype(np.float64)
    try:
        _, _, Vt = np.linalg.svd(rc, full_matrices=False)
        t = (rc @ Vt[0]).astype(np.float32)
    except: t = rc[:, 0].astype(np.float32)

    lo, hi = float(t.min()) - 1e-6, float(t.max()) + 1e-6
    edges = np.linspace(lo, hi, n_bins + 1)
    Tb = np.clip(np.digitize(t, edges) - 1, 0, n_bins - 1)
    n_classes = int(y.max()) + 1
    pT = np.bincount(Tb, minlength=n_bins).astype(np.float64) / len(y)
    HT = -np.sum(pT * np.log(pT + 1e-12))
    HTY = 0.0
    for c in range(n_classes):
        m = (y == c)
        if not m.any(): continue
        pc = m.mean()
        pTc = np.bincount(Tb[m], minlength=n_bins).astype(np.float64)
        pTc /= pTc.sum() + 1e-12
        HTY += pc * (-np.sum(pTc * np.log(pTc + 1e-12)))
    return float(max(0, HT - HTY))


def twonn_id(X, max_n=2000):
    if len(X) > max_n:
        X = X[np.random.choice(len(X), max_n, replace=False)]
    D = cdist(X, X)
    np.fill_diagonal(D, np.inf)
    n1 = np.partition(D, 1, axis=1)[:, 1]
    n2 = np.partition(D, 2, axis=1)[:, 2]
    mu = np.sort(n2 / (n1 + 1e-12))
    mu = mu[mu > 1 + 1e-8]
    if len(mu) < 10: return 1.0
    F_cdf = np.arange(1, len(mu) + 1) / len(mu)
    v = F_cdf < 0.9
    if v.sum() < 5: return 1.0
    return max(1.0, float(-np.polyfit(np.log(mu[v]), np.log(1 - F_cdf[v] + 1e-12), 1)[0]))


# ══════════════════════════════════════════════════════════════════════
# %% Cell 9 — Growth Controller (Dual-Score Width vs Depth)
# ══════════════════════════════════════════════════════════════════════

class GrowthController:
    """
    Dual-scoring growth: width AND depth are considered at every trigger,
    not sequentially.
    """
    def __init__(self, cooldown=6, delta_acc=0.003, acc_thresh=0.95,
                 max_params=500_000, overfit_gap_thresh=0.18, prune_cooldown=15):
        self.cooldown = cooldown
        self.delta_acc = delta_acc
        self.acc_thresh = acc_thresh
        self.max_params = max_params
        self.overfit_gap_thresh = overfit_gap_thresh
        self.prune_cooldown = prune_cooldown
        self.last_grow = -cooldown
        self.last_prune = -prune_cooldown

    def should_grow(self, epoch, accs, n_params):
        if epoch - self.last_grow < self.cooldown:
            return False, "cooldown"
        if n_params >= self.max_params:
            return False, "max_params"
        if len(accs) < 3:
            return False, "too_early"
        if accs[-1] > self.acc_thresh:
            return False, "above_threshold"
        w = min(5, len(accs) - 1)
        imp = (accs[-1] - accs[-1 - w]) / w
        if imp < self.delta_acc:
            return True, f"stalled (Δ={imp:.4f}/ep)"
        return False, f"improving ({imp:.4f}/ep)"

    def decide_growth_type(self, model, eff_rank_val, rep_id_val, data_id_val):
        """
        Dual-score: compare width saturation vs depth need.
        Width score: how saturated are current neurons (eff_rank / width)
        Depth score: representation gap relative to width capacity
        """
        w = model.mlp_width
        n_blk = model.n_blocks

        # Width saturation: if eff_rank is close to width, neurons are fully used
        width_saturation = eff_rank_val / (w + 1e-8)

        # Depth need: if rep_id growth has stalled relative to width growth
        rep_gap = (data_id_val - rep_id_val) / (data_id_val + 1e-8)
        depth_score = width_saturation * rep_gap  # high when width is saturated AND gap is large

        # Prefer depth when width is >60% saturated AND we have <6 blocks
        if width_saturation > 0.6 and n_blk < 6 and depth_score > 0.3:
            return "depth"
        return "width"

    def should_prune(self, epoch, train_acc, test_acc):
        if epoch - self.last_prune < self.prune_cooldown:
            return False
        gap = train_acc - test_acc
        if gap > self.overfit_gap_thresh:
            return True
        return False


# ══════════════════════════════════════════════════════════════════════
# %% Cell 10 — Training Loop
# ══════════════════════════════════════════════════════════════════════

EPOCHS = 120
LR_INIT = 0.01
LR_MIN = 1e-4

# Create model
model = NeuroplasticityNet(
    conv_channels=(16, 32, 64),
    init_mlp_width=64,
    init_blocks=2,
    n_classes=10
).to(DEVICE)

print(f"\n{'='*70}")
print(f"  EXPERIMENT 6: COMPLETE NEUROPLASTICITY")
print(f"{'='*70}")
print(f"Model: {model.n_params():,} params")
print(f"Conv: [16, 32, 64] → MLP width={model.mlp_width}, blocks={model.n_blocks}")
print(f"Device: {DEVICE}")

# Select fixed GradCAM samples (one per class)
gradcam_samples = []
gradcam_labels = []
seen_classes = set()
for img, label in raw_test_set:
    if label not in seen_classes:
        gradcam_samples.append(img)
        gradcam_labels.append(label)
        seen_classes.add(label)
    if len(seen_classes) == 10:
        break

# Controller
ctrl = GrowthController(max_params=500_000)
optimizer = optim.SGD(model.parameters(), lr=LR_INIT, momentum=0.9, weight_decay=5e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=LR_MIN)
criterion = nn.CrossEntropyLoss()

# History
hist = defaultdict(list)
hist['data_id'] = 0.0
growths = []
prunes = []

# Compute data ID
print("\nComputing data intrinsic dimensionality...")
test_feats = []
test_labels_np = []
with torch.no_grad():
    for xb, yb in test_loader:
        test_feats.append(xb.view(xb.size(0), -1).numpy())
        test_labels_np.append(yb.numpy())
        if len(test_feats) * 256 >= 2000:
            break
test_feats_np = np.concatenate(test_feats)[:2000]
data_id = twonn_id(test_feats_np)
hist['data_id'] = data_id
print(f"Data ID = {data_id:.2f}")

# Initial GradCAM
print("\nInitial GradCAM snapshot...")
snapshot_gradcam(model, gradcam_samples, gradcam_labels, 0, DEVICE, tag="_init")

# Training
print(f"\nTraining for {EPOCHS} epochs...")
print("-" * 80)

t0 = time.time()
for epoch in range(1, EPOCHS + 1):
    # ── Train ──
    model.train()
    running_loss = 0.0
    correct, total = 0, 0
    for xb, yb in train_loader:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        out = model(xb)
        loss = criterion(out, yb)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * xb.size(0)
        correct += (out.argmax(1) == yb).sum().item()
        total += xb.size(0)

    train_loss = running_loss / total
    train_acc = correct / total

    # ── Evaluate ──
    model.eval()
    correct_te, total_te = 0, 0
    with torch.no_grad():
        for xb, yb in test_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            out = model(xb)
            correct_te += (out.argmax(1) == yb).sum().item()
            total_te += xb.size(0)
    test_acc = correct_te / total_te

    # ── IT Metrics (every 5 epochs) ──
    if epoch % 5 == 0 or epoch <= 3 or epoch == EPOCHS:
        er = effective_rank(model)
        fi = fisher_trace(model, test_loader, DEVICE)
        mi = mutual_info_ib(model, test_loader, DEVICE)
        reps = model.represent(
            torch.cat([xb for xb, _ in [next(iter(test_loader))]])[:2000].to(DEVICE)
        ).cpu().numpy()
        rid = twonn_id(reps)
    else:
        er = hist['er'][-1] if hist['er'] else 1.0
        fi = hist['fi'][-1] if hist['fi'] else 0.0
        mi = hist['mi'][-1] if hist['mi'] else 0.0
        rid = hist['rid'][-1] if hist['rid'] else 1.0

    hist['epoch'].append(epoch)
    hist['tr_acc'].append(train_acc)
    hist['te_acc'].append(test_acc)
    hist['loss'].append(train_loss)
    hist['params'].append(model.n_params())
    hist['width'].append(model.mlp_width)
    hist['nblk'].append(model.n_blocks)
    hist['er'].append(er)
    hist['fi'].append(fi)
    hist['mi'].append(mi)
    hist['rid'].append(rid)

    status = ""

    # ── Growth Check ──
    do_grow, reason = ctrl.should_grow(epoch, hist['tr_acc'], model.n_params())
    if do_grow:
        old_p = model.n_params()
        kind = ctrl.decide_growth_type(model, er, rid, data_id)

        if kind == "depth":
            new_val = grow_depth(model)
            status = f" ★ DEPTH ↕ → {new_val} blocks"
        else:
            new_val = grow_width(model, WIDTH_DELTA)
            status = f" ★ WIDTH ↔ → {new_val}"

        new_p = model.n_params()
        growths.append((epoch, kind, old_p, new_p, reason))
        ctrl.last_grow = epoch
        model.to(DEVICE)

        # Rebuild optimizer
        optimizer = optim.SGD(model.parameters(), lr=scheduler.get_last_lr()[0],
                              momentum=0.9, weight_decay=5e-4)

        # GradCAM snapshot after growth
        snapshot_gradcam(model, gradcam_samples, gradcam_labels, epoch, DEVICE,
                         tag=f"_grow_{kind}")

    # ── Prune Check ──
    if ctrl.should_prune(epoch, train_acc, test_acc):
        print(f"  [Pruning triggered] train-test gap = {train_acc - test_acc:.3f}")
        n_pruned = synaptic_pruning_cycle(model, train_loader, DEVICE, prune_ratio=0.08)
        if n_pruned > 0:
            prunes.append((epoch, n_pruned, model.n_params()))
            ctrl.last_prune = epoch
            status += f" ✂ PRUNE {n_pruned} neurons"
            model.to(DEVICE)

            # Rebuild optimizer
            optimizer = optim.SGD(model.parameters(), lr=scheduler.get_last_lr()[0],
                                  momentum=0.9, weight_decay=5e-4)

            # GradCAM snapshot after pruning
            snapshot_gradcam(model, gradcam_samples, gradcam_labels, epoch, DEVICE,
                             tag="_post_prune")

    # ── Conv importance (every 20 epochs) ──
    if epoch % 20 == 0:
        conv_scores = conv_importance_scores(model, test_loader, DEVICE)
        print(f"    [ConvImportance] {['%.3f' % s for s in conv_scores]}")

    scheduler.step()

    # ── Logging ──
    if epoch % 5 == 0 or epoch <= 3 or do_grow or epoch == EPOCHS or 'PRUNE' in status:
        gap = data_id - rid
        print(f"  Ep {epoch:3d} | tr {train_acc:.3f} te {test_acc:.3f} | "
              f"loss {train_loss:.3f} | p={model.n_params():>7,} "
              f"w={model.mlp_width:3d} b={model.n_blocks} | "
              f"ER={er:.1f} MI={mi:.2f} RID={rid:.1f} gap={gap:.1f} | "
              f"{time.time()-t0:.0f}s{status}")

    if epoch % 20 == 0:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        # Checkpoint to Drive every 20 epochs
        ckpt = {
            'epoch': epoch,
            'model_state': model.state_dict(),
            'optimizer_state': optimizer.state_dict(),
            'hist': dict(hist),
            'growths': growths,
            'prunes': prunes,
        }
        ckpt_path = os.path.join(OUT_DIR, f'checkpoint_ep{epoch:03d}.pt')
        torch.save(ckpt, ckpt_path)
        print(f"    [Checkpoint] Saved → {ckpt_path}")

# Final GradCAM
snapshot_gradcam(model, gradcam_samples, gradcam_labels, EPOCHS, DEVICE, tag="_final")

elapsed = time.time() - t0
print("-" * 80)
print(f"Done in {elapsed:.0f}s")
print(f"Final: {model.n_params():,} params, w={model.mlp_width}, b={model.n_blocks}")
print(f"Train: {hist['tr_acc'][-1]:.3f}, Test: {hist['te_acc'][-1]:.3f}")
print(f"Growth events: {len(growths)}")
for g in growths:
    print(f"  Ep {g[0]:3d}: {g[1]:5s} {g[2]:,} → {g[3]:,} | {g[4]}")
print(f"Prune events: {len(prunes)}")
for p in prunes:
    print(f"  Ep {p[0]:3d}: pruned {p[1]} neurons → {p[2]:,} params")


# ══════════════════════════════════════════════════════════════════════
# %% Cell 11 — Save Results
# ══════════════════════════════════════════════════════════════════════

results = {
    'history': {k: [float(v) for v in vals] if isinstance(vals, list) else float(vals)
                for k, vals in hist.items()},
    'growths': [{'epoch': e, 'kind': k, 'before': b, 'after': a, 'reason': r}
                for e, k, b, a, r in growths],
    'prunes': [{'epoch': e, 'n_pruned': n, 'params_after': p}
               for e, n, p in prunes],
    'final': {
        'params': model.n_params(),
        'width': model.mlp_width,
        'blocks': model.n_blocks,
        'train_acc': hist['tr_acc'][-1],
        'test_acc': hist['te_acc'][-1],
    }
}

with open(os.path.join(OUT_DIR, 'experiment6_results.json'), 'w') as f:
    json.dump(results, f, indent=2)
print(f"\n[Save] Results → {OUT_DIR}/experiment6_results.json")

# Save model
torch.save(model.state_dict(), os.path.join(OUT_DIR, 'experiment6_model.pt'))
print(f"[Save] Model → {OUT_DIR}/experiment6_model.pt")


# ══════════════════════════════════════════════════════════════════════
# %% Cell 12 — Generate Summary Figures
# ══════════════════════════════════════════════════════════════════════

BG = '#0D1117'; PBG = '#161B22'
C = {'tr':'#58A6FF','te':'#3FB950','loss':'#F0883E','par':'#BC8CFF',
     'w':'#FF7B72','d':'#FFA657','er':'#79C0FF','fi':'#D2A8FF',
     'mi':'#7EE787','ri':'#58A6FF','di':'#F85149','gap':'#F8514933',
     'prune':'#F778A1'}

def sax(ax):
    ax.set_facecolor(PBG)
    ax.tick_params(colors='#8B949E', labelsize=8)
    for s in ax.spines.values(): s.set_color('#30363D')
    ax.grid(True, alpha=0.15, color='#484F58')

eps = hist['epoch']

# Fig 1: Accuracy + Loss + Params
fig, axes = plt.subplots(1, 3, figsize=(16, 4.5), facecolor=BG)
fig.subplots_adjust(wspace=0.35, top=0.85, bottom=0.18)
fig.suptitle('Experiment 6: Conv + SkipMLP + Pruning', color='white', fontsize=14, fontweight='bold')

a = axes[0]; sax(a)
a.plot(eps, hist['tr_acc'], color=C['tr'], lw=2, label='Train')
a.plot(eps, hist['te_acc'], color=C['te'], lw=2, label='Test')
for g in growths: a.axvline(g[0], color=C['w'] if g[1]=='width' else C['d'], lw=1.2, ls='--', alpha=0.6)
for p in prunes: a.axvline(p[0], color=C['prune'], lw=1.2, ls=':', alpha=0.6)
a.set_title('Accuracy', color='white', fontsize=11, fontweight='bold')
a.legend(fontsize=7, facecolor=PBG, labelcolor='white', framealpha=0.7)

a = axes[1]; sax(a)
a.plot(eps, hist['loss'], color=C['loss'], lw=2)
for g in growths: a.axvline(g[0], color=C['w'] if g[1]=='width' else C['d'], lw=1.2, ls='--', alpha=0.6)
for p in prunes: a.axvline(p[0], color=C['prune'], lw=1.2, ls=':', alpha=0.6)
a.set_title('Loss', color='white', fontsize=11, fontweight='bold')

a = axes[2]; sax(a)
a.plot(eps, [p/1000 for p in hist['params']], color=C['par'], lw=2)
for g in growths: a.axvline(g[0], color=C['w'] if g[1]=='width' else C['d'], lw=1.2, ls='--', alpha=0.6)
for p in prunes: a.axvline(p[0], color=C['prune'], lw=1.2, ls=':', alpha=0.6)
a.set_title('Parameters (K)', color='white', fontsize=11, fontweight='bold')

fig.legend(handles=[
    Line2D([0],[0], color=C['w'], ls='--', lw=2, label='Width ↔'),
    Line2D([0],[0], color=C['d'], ls='--', lw=2, label='Depth ↕'),
    Line2D([0],[0], color=C['prune'], ls=':', lw=2, label='Prune ✂'),
], loc='lower center', ncol=3, fontsize=9, facecolor=PBG, labelcolor='white',
   framealpha=0.8, bbox_to_anchor=(0.5, 0.0))
plt.savefig(os.path.join(OUT_DIR, 'exp6_fig1.png'), dpi=140, bbox_inches='tight', facecolor=BG)
plt.close()

# Fig 2: IT Signals
fig, axes = plt.subplots(1, 3, figsize=(16, 4.5), facecolor=BG)
fig.subplots_adjust(wspace=0.35, top=0.85, bottom=0.18)
fig.suptitle('Experiment 6: IT Signals', color='white', fontsize=14, fontweight='bold')

for i, (k, lbl, clr) in enumerate([('er','Effective Rank',C['er']),('fi','Fisher Trace',C['fi']),('mi','I(T;Y)',C['mi'])]):
    a = axes[i]; sax(a)
    a.plot(eps, hist[k], color=clr, lw=2)
    for g in growths: a.axvline(g[0], color=C['w'] if g[1]=='width' else C['d'], lw=1.2, ls='--', alpha=0.6)
    for p in prunes: a.axvline(p[0], color=C['prune'], lw=1.2, ls=':', alpha=0.6)
    a.set_title(lbl, color='white', fontsize=11, fontweight='bold')

plt.savefig(os.path.join(OUT_DIR, 'exp6_fig2.png'), dpi=140, bbox_inches='tight', facecolor=BG)
plt.close()

# Fig 3: Complexity gap
fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor=BG, gridspec_kw={'width_ratios': [2, 1]})
fig.subplots_adjust(wspace=0.3, top=0.85, bottom=0.18)
fig.suptitle('Experiment 6: Complexity Gap & Architecture', color='white', fontsize=14, fontweight='bold')

a = axes[0]; sax(a)
a.plot(eps, hist['rid'], color=C['ri'], lw=2.5, label='Rep ID')
a.axhline(data_id, color=C['di'], ls='--', lw=2, label=f'Data ID={data_id:.1f}')
a.fill_between(eps, hist['rid'], data_id,
               where=[r < data_id for r in hist['rid']],
               color=C['gap'], alpha=0.3, label='Gap')
for g in growths: a.axvline(g[0], color=C['w'] if g[1]=='width' else C['d'], lw=1.2, ls='--', alpha=0.6)
for p in prunes: a.axvline(p[0], color=C['prune'], lw=1.2, ls=':', alpha=0.6)
a.set_title('Neuroplasticity Signal', color='white', fontsize=11, fontweight='bold')
a.legend(fontsize=8, facecolor=PBG, labelcolor='white', framealpha=0.7)

a = axes[1]; sax(a)
a.plot(eps, hist['width'], color=C['w'], lw=2, label='Width')
a2 = a.twinx()
a2.plot(eps, hist['nblk'], color=C['d'], lw=2, ls='--', label='Blocks')
a2.tick_params(colors='#8B949E', labelsize=8)
a.set_title('Architecture', color='white', fontsize=11, fontweight='bold')
a.set_ylabel('Width', color='#C9D1D9', fontsize=9)
a2.set_ylabel('Blocks', color=C['d'], fontsize=9)
lines1, labels1 = a.get_legend_handles_labels()
lines2, labels2 = a2.get_legend_handles_labels()
a.legend(lines1+lines2, labels1+labels2, fontsize=8, facecolor=PBG, labelcolor='white', framealpha=0.7)

plt.savefig(os.path.join(OUT_DIR, 'exp6_fig3.png'), dpi=140, bbox_inches='tight', facecolor=BG)
plt.close()

print(f"\n[✓] All figures saved to {OUT_DIR}/")
print(f"[✓] GradCAM snapshots: {len([f for f in os.listdir(OUT_DIR) if 'gradcam' in f])} files")
print("\n" + "="*70)
print("  EXPERIMENT 6 COMPLETE")
print("="*70)

